[package]
name = "ring-channel"
version = "0.1.0"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Never blocking, bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["asynchronous"]

[dependencies]
crossbeam-queue = "0.1.2"
derivative = "1.0.2"