[package]
name = "ring-channel"
version = "0.1.0"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Never blocking, bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["concurrency", "asynchronous"]

[dependencies]
crossbeam-queue = "0.1.2"
derivative = "1.0.2"

[dev-dependencies]
criterion = "0.2.10"
proptest = "0.9.2"
rayon = "1.0.3"

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "throughput"
harness = false
