[package]
name = "ring-channel"
version = "0.8.3"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["concurrency", "asynchronous"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["futures_api"]
futures_api = ["futures"]

[badges]
codecov = { repository = "brunocodutra/ring-channel" }

[dependencies]
crossbeam-queue = "0.3.1"
crossbeam-utils = "0.8.1"
derivative = "2.2.0"
futures = { version = "0.3.12", optional = true }
smallvec = "1.6.1"
spinning_top = "0.2.2"

[dev-dependencies]
criterion = "0.3.4"
mockall = "0.10.2"
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.0"
smol = "1.2.5"

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "futures"
harness = false
required-features = ["futures_api"]

[lib]
bench = false
