[package]
name = "ring-channel"
version = "0.8.2"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["concurrency", "asynchronous"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["futures_api"]
futures_api = ["futures"]

[badges]
codecov = { repository = "brunocodutra/ring-channel" }

[dependencies]
crossbeam-queue = "0.2.3"
crossbeam-utils = "0.7.2"
derivative = "2.1.1"
futures = { version = "0.3.5", optional = true }
smallvec = "1.4.2"
spinning_top = "0.2.2"

[dev-dependencies]
criterion = "0.3.3"
futures = { version = "0.3.5", features = ["thread-pool"] }
mockall = "0.8.1"
proptest = "0.10.1"
proptest-derive = "0.2.0"
rayon = "1.4.1"

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "futures"
harness = false
required-features = ["futures_api"]

[lib]
bench = false
