[package]
name = "ring-channel"
version = "0.6.1"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Never blocking, bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["concurrency", "asynchronous"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["futures_api"]
futures_api = ["futures-preview"]

[badges]
codecov = { repository = "brunocodutra/ring-channel" }

[dependencies]
crossbeam-queue = "0.1.2"
crossbeam-utils = "0.6.6"
derivative = "1.0.3"
futures-preview = { version = "0.3.0-alpha.19", optional = true }
spin = "0.5.2"
smallvec = "0.6.10"

[dev-dependencies]
criterion = "0.3.0"
mockall = "0.5.1"
proptest = "0.9.4"
proptest-derive = "0.1.2"
rayon = "1.2.0"

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "futures"
harness = false
required-features = ["futures_api"]

[lib]
bench = false
