[package]
name = "ring-channel"
version = "0.6.0"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Never blocking, bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["concurrency", "asynchronous"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["futures_api"]
futures_api = ["futures-preview"]

[badges]
travis-ci = { repository = "brunocodutra/ring-channel" }
codecov = { repository = "brunocodutra/ring-channel" }

[dependencies]
crossbeam-queue = "0.1.2"
crossbeam-utils = "0.6.6"
derivative = "1.0.2"
futures-preview = { version = "0.3.0-alpha.17", optional = true }

[dev-dependencies]
criterion = "0.2.10"
proptest = "0.9.4"
rayon = "1.1.0"

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "futures"
harness = false
required-features = ["futures_api"]

[lib]
bench = false
