[package]
name = "ring-channel"
version = "0.7.0"
edition = "2018"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
description = "Never blocking, bounded MPMC channel abstraction on top of a ring buffer"
repository = "https://github.com/brunocodutra/ring-channel.git"
license = "MIT"
readme = "README.md"
keywords = ["mpmc", "channel", "asynchronous", "ring"]
categories = ["concurrency", "asynchronous"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["futures_api"]
futures_api = ["futures"]

[badges]
codecov = { repository = "brunocodutra/ring-channel" }

[dependencies]
crossbeam-queue = "0.2.1"
crossbeam-utils = "0.7.0"
derivative = "1.0.3"
futures = { version = "0.3.1", optional = true }
smallvec = "1.1.0"
spin = "0.5.2"

[dev-dependencies]
criterion = "0.3.0"
mockall = "0.6.0"
proptest = "0.9.4"
proptest-derive = "0.1.2"
rayon = "1.3.0"

[dev-dependencies.futures]
version = "*"
features = ["thread-pool"]

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "futures"
harness = false
required-features = ["futures_api"]

[lib]
bench = false
